### PR TITLE
Use golang 1.17.3 in contrib/tkn-image/Dockerfile

### PR DESCRIPTION
**Pull request by mattysweeps**
# Changes

- Bump the default GOLANG_VERSION to 1.17.3
  The image was not building with the existing default value, 1.13.* due
  to the use of embeded files

TESTED:
```
docker build --file=contrib/tkn-image/Dockerfile --target=tkn --tag tkn:latest .
```

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [ ] Includes [tests](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if functionality changed/added)
- [ ] Run the code checkers with `make check`
- [ ] Regenerate the manpages, docs and go formatting with `make generated`
- [ ] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)

_See [the contribution guide](https://github.com/tektoncd/cli/blob/master/CONTRIBUTING.md)
for more details._

# Release Notes

### CODE REVIEW

**Comment by piyush-garg** [comment]
@mattysweeps Currently the Dockerfile in this repo is not getting used, the one which is getting used is https://github.com/tektoncd/plumbing/blob/main/tekton/images/tkn/Dockerfile

**Review by vdemeester — APPROVED** [review]

**Comment by bendory** [comment]
/lgtm
but robot doesn't like me yet 😿

**Review by vdemeester — COMMENTED** [review]
/lgtm

**Pull request merged**
