### PR TITLE
Add triggers version info to the version command

### PR DESCRIPTION
**Pull request by savitaashture**
Issue: https://github.com/tektoncd/cli/issues/980
# Changes
Add triggers version information to existing version command
**Output:**
```
tkn version
Client version: dev
Pipeline version: v0.12.0
Triggers version: v0.5.0
```

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [x] Includes [tests](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if functionality changed/added)
- [x] Run the code checkers with `make check`
- [x] Regenerate the manpages, docs and go formatting with `make generated`
- [x] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)

_See [the contribution guide](https://github.com/tektoncd/cli/blob/master/CONTRIBUTING.md)
for more details._

# Release Notes

```
None
```

### CODE REVIEW

**Comment by pradeepitm12** [comment]
Not sure why do I get the unknown for Trigger Version

**Comment by savitaashture** [comment]
> Not sure why do I get the unknown for Trigger Version
> 
> ```
> ./tkn version
> Client version: dev
> Pipeline version: v0.11.3
> Triggers version: unknown
> ```

Hi @pradeepitm12 reason for that is in the latest(0.5.0) triggers release the value for the label `app.kubernetes.io/name` changed from `tekton-triggers` to `controller` 
As you have installed v0.4.0 version of triggers there is a mismatch in the labels so its giving `unknown`

I have started discussion in [slack](https://tektoncd.slack.com/archives/CL3T51NRF/p1589451766036200) 

Once i get any reply i  will update PR accordingly 

Thank you

**Comment by savitaashture** [comment]
@vdemeester @pradeepitm12 
PR is ready for another review Thank you

**Comment by pradeepitm12** [comment]
> @vdemeester @pradeepitm12
> PR is ready for another review Thank you

Thanks for the update @savitaashture

**Pull request merged**
