### PR TITLE
Drop cobra fork and rework the shell completion system

### PR DESCRIPTION
**Pull request by chmouel**
# Changes

Adapted the completion we had previously to the new completion system from
cobra 1.0.

I started to use the client-go directly but since there is no caching, the
<Tab><Tab> is not very usuable since super slow. So using the kuebctl binrary directly instead
(I can't use tkn since caching is not there as well) to get the
completions.

This is how we were doing it previously (using kubectl or tkn) and
completions should be much faster. And bonus, we have some proper completion for powershell/fish and others added for free. (not tested).

It doesn't pickup the completion on `tkn hub`, so we wil need to figure out on how to do this for commands that gets pulled up by deps.

Note: this PR has two diffsets on purpose, to make it easier to review/track
history. The split is between updating the new library and the second split to
add all completions to all commands.

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [X] Includes [tests](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if functionality changed/added)
- [X] Run the code checkers with `make check`
- [X] Regenerate the manpages, docs and go formatting with `make generated`
- [X] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)

# Release Notes

```release-note
The cobra fork we were using previously has been dropped and all completions
has been modified to use latest cobra shell completion system.
```

### CODE REVIEW

**Comment by chmouel** [comment]
There is as way to get inline completion for flags, i.e: --service-account <TAB> to complete the serviceaccount as we had before, this is the example from the helm sources : 

https://github.com/helm/helm/blob/e71d38b414eb92912a87e6d1e751e88ee8fc57ea/cmd/helm/get_notes.go#L62-L71

Will make a further patch later on to address thoses as this will be another big one..

Ready for review this one to make it easier...

/hold cancel

**Comment by chmouel** [comment]
We probably going to have to figure how to do this with `tkn hub` too...

**Comment by vdemeester** [comment]
cc @mattmoor

**Review by pradeepitm12 — APPROVED** [review]
/lgtm

**Pull request merged**
