### PR TITLE
Add command for listing pipelineruns

### PR DESCRIPTION
**Pull request by pradeepitm12**
This will add command to list all the pipelineruns
in a given namespace

eg - tkn pipelineruns list -n namespace

Signed-off-by: Pradeep Kumar pradkuma@redhat.com

### CODE REVIEW

**Comment by pradeepitm12** [comment]
I signed it!

**Comment by vdemeester** [comment]
@pradeepitm12 this is gonna need a rebase after https://github.com/tektoncd/cli/pull/17 :sweat_smile:

**Comment by chmouel** [comment]
probably need to be refactored with what sunil has been doing

**Comment by sthaha** [comment]
closing this in favour of https://github.com/tektoncd/cli/pull/19

**Pull request closed without merging**
