### PR TITLE
Remove unnecessary test util.

### PR DESCRIPTION
**Pull request by 16yuki0702**
# Changes
This is a trivial PR.
related issue is https://github.com/tektoncd/cli/issues/520

interactive tests are already disabled,
but ```pkg/cmd/pipelineresource/resource_testUtil.go``` is unnecessary and can be removed.

this PR just remove this file, and there are no changes about tests.
# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [ ] Includes [tests](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if functionality changed/added)
- [ ] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)
- [ ] Regenerate the manpages and docs with `make docs` and `make man` if needed.
- [ ] Run the code checkers with `make check`
- [ ] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)

_See [the contribution guide](https://github.com/tektoncd/cli/blob/master/CONTRIBUTING.md)
for more details._

# Release Notes

```
no effect on features.
```

### CODE REVIEW

**Comment by chmouel** [comment]
/lgtm

Looking Good! 🤙🏽

**Comment by chmouel** [comment]
/hold

but we disabled the interactive tests but we may very much want to enable them again as working, what do you think we do, keep those files in the repo or remove them and resurrect them when we are working again on it ?

**Comment by 16yuki0702** [comment]
I think it is better remove this file for now and if we want enable interactive tests again we should modify all interactive tests at once.

because it is clearly what files we should modify, and it is possible all interactive tests are involved about the flakiness.

but I know this approarches of cons, it is hard to modify all tests at once because there a lot of tests :joy:  !!

**Pull request closed without merging**
