### PR TITLE
Fix CLI installation instructions for deb-based distros

### PR DESCRIPTION
**Pull request by tpiperatgod**
# Changes
> I have reported this issue in the website repo: [issue#281](https://github.com/tektoncd/website/issues/281) 

Use `dpkg` instead of `rpm` to install the `.deb` package, and before that you need to use `curl -LO` to fetch the package.

The changes here follow the [PR#244](https://github.com/tektoncd/website/pull/244).

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [ ] Includes [tests](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if functionality changed/added)
- [ ] Run the code checkers with `make check`
- [ ] Regenerate the manpages, docs and go formatting with `make generated`
- [ ] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)

_See [the contribution guide](https://github.com/tektoncd/cli/blob/master/CONTRIBUTING.md)
for more details._

# Release Notes

Signed-off-by: laminar <fangtian@kubesphere.io>

### CODE REVIEW

**Comment by vinamra28** [comment]
/ok-to-test
/lgtm
@tpiperatgod can you please sign the SLA as well?

**Comment by tpiperatgod** [comment]
> /ok-to-test
> /lgtm
> @tpiperatgod can you please sign the SLA as well?

Okey, I have signed the CLA. You mean this, right?

**Review by vdemeester — APPROVED** [review]
/meow
Thanks @tpiperatgod

**Pull request merged**
