### PR TITLE
Improve `tkn chain` log format

### PR DESCRIPTION
**Pull request by concaf**
Prior to this commit, `tkn chain` logs look like:

```
$ tkn chains payload build-push-run-output-image-p229w
sync /dev/stderr: invalid argument
{"level":"info","ts":1654352100.0164135,"caller":"tekton/tekton.go:134","msg":"Retrieving payload on TaskRun default/build-push-run-output-image-p229w"}
{"level":"info","ts":1654352100.0164497,"caller":"tekton/tekton.go:86","msg":"Retrieving annotation \"chains.tekton.dev/payload-taskrun-6e2f020b-7d50-4022-8064-049680f72d32\" on TaskRun default/build-push-run-output-image-p229w"}
No payloads found for taskrun build-push-run-output-image-p229w
```

and after this commit they look like:

```
$ ./tkn chains payload build-push-run-output-image-p229w
sync /dev/stderr: invalid argument
Retrieving payload on TaskRun default/build-push-run-output-image-p229w
Retrieving annotation "chains.tekton.dev/payload-taskrun-6e2f020b-7d50-4022-8064-049680f72d32" on TaskRun default/build-push-run-output-image-p229w
No payloads found for taskrun build-push-run-output-image-p229w
```

which is more in line with how `tkn` logs look like in general.

# Changes

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [x] Includes [tests](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if functionality changed/added)
- [x] Run the code checkers with `make check`
- [x] Regenerate the manpages, docs and go formatting with `make generated`
- [x] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)

_See [the contribution guide](https://github.com/tektoncd/cli/blob/master/CONTRIBUTING.md)
for more details._

# Release Notes

```release-note
Improve log format for `tkn chains` subcommand
```

### CODE REVIEW

**Comment by concaf** [comment]
```release-note
Improve log format for `tkn chains` subcommand
```

**Review by pradeepitm12 — APPROVED** [review]
/lgtm

**Pull request merged**
