### PR TITLE
Add Bug, Feature, and Free Form Issue Templates

### PR DESCRIPTION
**Pull request by danielhelfand**
Following form of `kn` issue templates, this pull request adds templates to better gather information for bug reports and feature requests and also adds a free form template for other cases.

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [ ] Includes [tests](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if functionality changed/added)
- [ ] Run the code checkers with `make check`
- [ ] Regenerate the manpages, docs and go formatting with `make generated`
- [x] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)

# Release Notes

```
N/A
```

### CODE REVIEW

**Comment by danielhelfand** [comment]
Think build failure is related to https://github.com/tektoncd/plumbing/pull/430 and #1022. Will open separate pr to fix this.

**Comment by vdemeester** [comment]
@danielhelfand I think a rebase and all will be good ?

**Comment by danielhelfand** [comment]
> @danielhelfand I think a rebase and all will be good ?

Yup, should be good now after #1028 + rebase.

**Comment by chmouel** [comment]
/lgtm

Looking Good! 🤙🏽

**Pull request merged**
