### PR TITLE
Removed apt-key for deb-based install instructions

### PR DESCRIPTION
**Pull request by jgreenbow-userful**
# Changes

Updated gpg key import for PPA

Users may receive a warning every apt-get update due to apt-key deprecation
W: http://ppa.launchpad.net/tektoncd/cli/ubuntu/dists/eoan/InRelease: Key is stored in legacy trusted.gpg keyring (/etc/apt/trusted.gpg), see the DEPRECATION section in apt-key(8) for details.
Users on older versions of apt may require the bare binary key, instead of the keybox

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [x] ~Includes [tests](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if functionality changed/added)~
- [x] ~Run the code checkers with `make check`~
- [x] ~Regenerate the manpages, docs and go formatting with `make generated`~
- [x] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)

_See [the contribution guide](https://github.com/tektoncd/cli/blob/master/CONTRIBUTING.md)
for more details._

# Release Notes

### CODE REVIEW

**Comment by chmouel** [comment]
/ok-to-test

nice thank you

**Comment by chmouel** [comment]
(sorry about the CLA but we will need it to be signed to be able to merge this pr)

**Comment by jgreenbow-userful** [comment]
@chmouel no worries, I was just contributing the fix I tracked down for `apt` spam. I didn't have time on Friday to amend my commit message, or sign the CLA once I noted its existence in the contributer guide. I'll look at this later 👍

**Comment by jgreenbow-userful** [comment]
Hey there, I am totally new to open source contribution. I sync'd this branch with [tektoncd:main](https://github.com/tektoncd/cli), but that has produced an (unecessary) merge commit. My guess is that I should rebase my _tiny_ branch onto [tektoncd:main](https://github.com/tektoncd/cli) and let it test through again. Is it kosher to issue rewrites to my fork during a PR review, or should I preserve the history of syncing up my branch and keep the merge commit in?

**Comment by chmouel** [comment]
I think you good, it doesn't conflict or it will have tell you, 

/lgtm
/approve

**Pull request merged**
