### PR TITLE
Set default to False for Show Logs on TaskRun and PipelineRun

### LINKED ISSUE #455: Set Default to False for Show Logs for TaskRun and PipelineRun
It's a bit unexpected to immediately show logs after starting a task run or a pipeline run. I realize that this was an intentional feature added for pipeline runs and task runs, but I think it's not fair to assume that users will want to immediately see logs with the CLI. 

I think the `--show-logs` flag gives users the ability to control whether they immediately want to see logs, but we should not assume they will by default. 

I wanted to open this up to discussion and see if there were any strong opinions as for why logs should be shown by default. 

# Expected Behavior

Starting a pipeline run or task run will not immediately show logs.

# Actual Behavior

Logs are shown.

### PR DESCRIPTION
**Pull request by chmouel**
Closes #455

```
We do not show the logs anymore right after starting the pipeline, use
--showlog to see it
```

### CODE REVIEW

**Comment by piyush-garg** [comment]
Also, should we remove `--showlog=false` from the tests ?

**Comment by danielhelfand** [comment]
> Also, should we remove `--showlog=false` from the tests ?

It would be nice. With this change, I would think using `--showlog=false` would never really be needed. No issues if we want to do in a follow up pr though.

**Comment by chmouel** [comment]
Sounds good, i removed them from the tests and regenerated the docs, thanks,

**Pull request merged**
