### PR TITLE
Display workspaces in tkn task/clustertask/taskrun describe command

### LINKED ISSUE #1045: Task/TaskRun describe: display workspace
### Feature request

When doing a `tkn task describe` (and `tkn taskrun describe`) I would like to see the declared workspace in the output.

### Use case

Being able to see what workspace I need to provide to execute the task

### UI Example

```bash
$ tkn taskrun desc pipeline-release-run-z9557-unit-tests-jfttz
Name:              pipeline-release-run-z9557-unit-tests-jfttz
Namespace:         default
Task Ref:          golang-test
Service Account:   release-right-meow
Timeout:           1h0m0s
Labels:
 app.kubernetes.io/managed-by=tekton-pipelines
 tekton.dev/pipeline=pipeline-release
 tekton.dev/pipelineRun=pipeline-release-run-z9557
 tekton.dev/pipelineTask=unit-tests
 tekton.dev/task=golang-test

🌡️  Status

STARTED         DURATION    STATUS
4 minutes ago   ---         Failed(TaskRunValidationFailed)

Message

bound workspaces did not match declared workspaces: didn't provide required values: [source]

📨 Input Resources

No input resources

📨 Workspace

 NAME       RESOURCE REF
 ∙ source   tekton-pipelines-git-v0-14-0

📡 Output Resources

 No output resources

⚓ Params

 NAME        VALUE
 ∙ package   github.com/tektoncd/pipeline
 ∙ flags     -v -mod=vendor

🦶 Steps

No steps

🚗 Sidecars

No sidecars
                  
```

### PR DESCRIPTION
**Pull request by vinamra28**
# Changes

The workspaces declared in the clustertask/task/taskrun will be displayed in the output of their respective describe command.
- When we will do `tkn clustertask desc <ctname>` workspace name and description will be displayed in the output
- When we will do `tkn task desc <task-name>` workspace name and description will be displayed in the output
- When we will do `tkn taskrun desc <taskrun-name.`  `workspace name`, `subdir` and `workspace binding` will be displayed as part of output

Closes #1045 

sample TaskRun describe output is as follows :- 
```bash
$ tkn taskrun describe custom-volume-5tc6p
Name:        custom-volume-5tc6p
Namespace:   default
Timeout:     1h0m0s
Labels:
 app.kubernetes.io/managed-by=tekton-pipelines

🌡️  Status

STARTED       DURATION    STATUS
5 hours ago   1 minute    Succeeded

📨 Input Resources

 No input resources

📡 Output Resources

 No output resources

⚓ Params

 No params

📝 Results

 No results

📂 Workspaces

 NAME        SUB PATH        WORKSPACE BINDING
 ∙ custom    my-subdir       PersistentVolumeClaim (claimName=my-pvc)
 ∙ custom2   ---             PersistentVolumeClaim (claimName=my-pvc)
 ∙ custom3   testing         EmptyDir (emptyDir=)
 ∙ custom4   ---             ConfigMap (config=my-configmap,item=message=my-message.txt)
 ∙ custom5   ---             Secret (secret=my-secret)

🦶 Steps

 NAME              STATUS
 ∙ write           Completed
 ∙ read            Completed
 ∙ write2          Completed
 ∙ read2           Completed
 ∙ write3          Completed
 ∙ read3           Completed
 ∙ readconfigmap   Completed
 ∙ readsecret      Completed

🚗 Sidecars

No sidecars
```

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [X] Includes [tests](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if functionality changed/added)
- [X] Run the code checkers with `make check`
- [X] Regenerate the manpages, docs and go formatting with `make generated`
- [X] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)

_See [the contribution guide](https://github.com/tektoncd/cli/blob/master/CONTRIBUTING.md)
for more details._

# Release Notes
```release-note
- Display workspace name and description in the output of task/clustertask describe command
- Display workspace name, subdir and workspace binding in the output of taskrun describe command
```

### CODE REVIEW

**Review by vdemeester — COMMENTED** [review]
@vinamra28 looking good for `Task` and `ClusterTask`. Should we do `TaskRun` in a follow-up and get this merged ? :angel:

**Comment by vinamra28** [comment]
makes sense :+1: . Will remove WIP from this :sweat_smile:

**Review by vdemeester — COMMENTED** [review]
/lgtm
/cc @danielhelfand @pradeepitm12 @piyush-garg

**Pull request merged**
