### PR TITLE
Upgrade AlecAivazais/survey to v2.3.5

### PR DESCRIPTION
**Pull request by abayer**
# Changes

I was having trouble debugging some tests I was working on refactoring, and eventually realized this was due to https://github.com/AlecAivazis/survey/issues/408, which was fixed in survey v2.3.3.

This also ends up upgrading hinshun/vt10x, getting rid of the `NewVT10xTerminal` function we'd been calling in a few places, so I band-aided that by adding an equivalent function in `test/helper/helpers.go`.

/kind misc

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [x] Includes [tests](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if functionality changed/added)
- [x] Run the code checkers with `make check`
- [x] Regenerate the manpages, docs and go formatting with `make generated`
- [x] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)

_See [the contribution guide](https://github.com/tektoncd/cli/blob/master/CONTRIBUTING.md)
for more details._

# Release Notes

```release-note
NONE
```

### CODE REVIEW

**Comment by abayer** [comment]
Oh great, it fails cross-compiling for Windows!

```
GOOS=windows GOARCH=amd64 go build -mod=vendor  -o bin/tkn-windows-amd64 ./cmd/tkn
# github.com/hinshun/vt10x
vendor/github.com/hinshun/vt10x/vt_other.go:26:7: t.State.cur.attr undefined (type Cursor has no field or method attr, but does have Attr)
vendor/github.com/hinshun/vt10x/vt_other.go:27:7: t.State.cur.attr undefined (type Cursor has no field or method attr, but does have Attr)
make: *** [Makefile:61: amd64] Error 2
```

**Review by pradeepitm12 — APPROVED** [review]
/lgtm

**Pull request merged**
