### PR TITLE
Bump pipeline and triggers 🐤

### LINKED ISSUE #1181: Bump to pipeline v0.16.3 and triggers v0.8.1
Bump the vendor dependencies of tektoncd/pipeline v0.16.3 and tektoncd/triggers v0.8.1

/assign

### PR DESCRIPTION
**Pull request by vdemeester**
# Changes

- pipeline v0.16.3
- triggers v0.8.1

Closes #1181 

Signed-off-by: Vincent Demeester <vdemeest@redhat.com>

/cc @tektoncd/cli-maintainers 

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [ ] Includes [tests](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if functionality changed/added)
- [x] Run the code checkers with `make check`
- [x] Regenerate the manpages, docs and go formatting with `make generated`
- [x] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)

_See [the contribution guide](https://github.com/tektoncd/cli/blob/master/CONTRIBUTING.md)
for more details._

# Release Notes

```release-note
Bump pipeline to v0.16.3 and triggers to v0.8.1
```

### CODE REVIEW

**Comment by vdemeester** [comment]
```
github.com/tektoncd/cli/pkg/test imports
	github.com/tektoncd/triggers/test tested by
	github.com/tektoncd/triggers/test.test imports
	github.com/tektoncd/triggers/pkg/sink imports
	github.com/tektoncd/triggers/pkg/interceptors/bitbucket tested by
	github.com/tektoncd/triggers/pkg/interceptors/bitbucket.test imports
	github.com/tektoncd/pipeline/pkg/logging: module github.com/tektoncd/pipeline@latest found (v0.16.3), but does not contain package github.com/tektoncd/pipeline/pkg/logging
```

That's madness :joy_cat:

**Comment by vdemeester** [comment]
kinda blocked on https://github.com/tektoncd/triggers/pull/765

**Comment by savitaashture** [comment]
Raised another PR https://github.com/tektoncd/triggers/pull/767 and closing this because did lot of hacks and its becoming difficult to solve

**Comment by piyush-garg** [comment]
This will be resolved by https://github.com/tektoncd/triggers/pull/760 but I have the PR almost ready with all the changes required, just working on the Service Account one

**Pull request closed without merging**
