### PR TITLE
update deps - k8s deps are now v0.19.7

### PR DESCRIPTION
**Pull request by dprotaso**
This is bumping tekton deps to the latest 

We've dropped `replace` directives for k8s deps upstream (knative & tekton) so they shouldn't require manual updates anymore.

/kind cleanup

```release-note
NONE
```

/hold - there's breaking changes in trigger so i'll wait for that to be resolved prior to bumping k8s deps

### CODE REVIEW

**Comment by vdemeester** [comment]
/ok-to-test
/hold
Holding this for just after the release 0.16 of cli (which should happen early next week)

**Comment by dprotaso** [comment]
sorry - a dependency changed the case of a folder - i'll push that

**Comment by dprotaso** [comment]
I realize theres some deprecated properties the triggers api that have been removed.

I'll probably delay this given someone's already working on that https://github.com/tektoncd/cli/issues/1295

**Comment by dprotaso** [comment]
This is ready for a look now that a CLI release has been cut

**Comment by vdemeester** [comment]
/hold cancel
/approve
@dprotaso can you squash your commits ? 😛

**Comment by dprotaso** [comment]
> @dprotaso can you squash your commits ? 😛

Sure. Is there a reason why you don't have prow squash commits (ie. [change the prow config here](https://github.com/tektoncd/plumbing/blob/2c1808d75b38d6fcaae0a37f5a9dda50545af4c8/prow/config.yaml#L69))

**Review by piyush-garg — APPROVED** [review]
/lgtm

**Pull request merged**
