### PR TITLE
Added Scoop & PowerShell install on Windows

### PR DESCRIPTION
**Pull request by GrooveCS**
# Changes

1. Proofed and Edit content
1. Explicit information for `Tekton` and related resources
1. Created header sections for Mac OS X & Windows
1. Added `Scoop` and `PowerShell` Scripts to Windows section

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [X] Documentation modification, and following not applicable. 
- [ ] ~~Includes [tests](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if functionality changed/added)~~
- [ ] ~~Run the code checkers with `make check`~~
- [ ] ~~Regenerate the manpages, docs and go formatting with `make generated`~~
- [ ] ~~Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)~~

_See [the contribution guide](https://github.com/tektoncd/cli/blob/master/CONTRIBUTING.md)
for more details._

# Release Notes

### CODE REVIEW

**Comment by GrooveCS** [comment]
@barthy1, @piyush-garg & @ciriarte 

I rebased, resolved conflict, and merged. Please let me know what actions I need to take to move forward. 

Parris

**Review by GrooveCS — COMMENTED** [review]
Complete reviewing the patch.

**Review by vinamra28 — CHANGES_REQUESTED** [review]
@GrooveCS I see a few file changes which got already merged. Can you please try to rebase?
I am wondering why prow didn't added `needs-rebase` label :thinking:

**Comment by GrooveCS** [comment]
Hi @vinamra28,

I took the time to verify and review rebasing, and I believe it is correct now.

When you have a moment, can you review it? 

Thank you, P-)

**Comment by GrooveCS** [comment]
Hi @vinamra28

Let me know if I closer to doing this correctly?

Thanks, Parris

**Comment by vinamra28** [comment]
hi @GrooveCS, I guess you need to do `go mod vendor` since the tests logs are saying:
```
go: inconsistent vendoring in /home/prow/go/src/github.com/tektoncd/cli:
	github.com/spf13/cobra@v1.1.3: is explicitly required in go.mod, but vendor/modules.txt indicates github.com/spf13/cobra@v1.1.1

run 'go mod vendor' to sync, or use -mod=mod or -mod=readonly to ignore the vendor directory
```

**Comment by GrooveCS** [comment]
Hi @vinamra28, @sthaha, & @piyush-garg:

I complete the following:

1. Rebased to current main 
1. Functional tested the completion functionality
1. Run go mod vendor

Can you review my progress?

**Comment by vinamra28** [comment]
@GrooveCS can you please run `make check`. For me it's failing and giving the following
```
$ make check                          
Linting go files...
pkg/cmd/completion/completion.go:19: File is not `gofmt`-ed with `-s` (gofmt)
```

**Comment by GrooveCS** [comment]
Hi @vinamra28, 

I ran `go fmt ./...` and amended the commit.

**Comment by vinamra28** [comment]
@GrooveCS can you please run `make check` and `make generated` once before repushing?

**Comment by GrooveCS** [comment]
Yes, I will shortly.

**Comment by piyush-garg** [comment]
@GrooveCS Please do `make generated`

**Comment by GrooveCS** [comment]
Hi,
I'm closing this pull request and will revisit it in the future.

**Pull request closed without merging**
