### PR TITLE
Update log_reader.go EOFLOG to friendlier message

### PR DESCRIPTION
**Pull request by mattysweeps**
Replace `EOFLOG` with `Step completed` so streaming of log output is a little more user friendly.

# Changes

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [ ] Includes [tests](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if functionality changed/added)
- [ ] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)
- [ ] Regenerate the manpages and docs with `make docs` and `make man` if needed.
- [ ] Run the code checkers with `make check`
- [ ] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)

_See [the contribution guide](https://github.com/tektoncd/cli/blob/master/CONTRIBUTING.md)
for more details._

# Release Notes

```
release-note
```

### CODE REVIEW

**Comment by danielhelfand** [comment]
@mattysweeps Thanks for your pr and helping us make this more user friendly. Could you please look through the failing unit tests and make updates based on the new output?

More than happy to help if you need some clarity.

**Comment by danielhelfand** [comment]
@mattysweeps Were you still interested in finishing this pr? I think this would be a nice improvement over the current logging messaging. Otherwise, we can close this and give you a coauthorshop commit.

**Comment by mattysweeps** [comment]
@danielhelfand I plan to, I've just been busy.
I see this PR is closed, has an equivalent commit been added to the project?

**Comment by danielhelfand** [comment]
/reopen 

Hey, I’m sorry! Please take your time with this.

**Pull request closed without merging**
