### PR TITLE
Bump chocolatey package to 0.28.0

### PR DESCRIPTION
**Pull request by vinamra28**
# Changes

Signed-off-by: vinamra28 <jvinamra776@gmail.com>
# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [ ] Includes [tests](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if functionality changed/added)
- [ ] Run the code checkers with `make check`
- [ ] Regenerate the manpages, docs and go formatting with `make generated`
- [ ] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)

_See [the contribution guide](https://github.com/tektoncd/cli/blob/master/CONTRIBUTING.md)
for more details._

# Release Notes
```release-note
NONE
```

### CODE REVIEW

**Comment by chmouel** [comment]
goreleaser now supports chocolatery in latest version, maybe we should just include it part of goreleaser? 

https://goreleaser.com/customization/chocolatey/

**Comment by vinamra28** [comment]
> goreleaser now supports chocolatery in latest version, maybe we should just include it part of goreleaser?
> 
> https://goreleaser.com/customization/chocolatey/

definitely 👍🏻

**Pull request merged**
