### PR TITLE
Add a goreleaser configuration file for the release

### PR DESCRIPTION
**Pull request by vdemeester**
# Changes

This will help us release the cli using Tekton Pipeline and
goreleaser. It will build any GOOS/GOARCH combination we need, and can
even generate packages and container images.

/cc @sthaha @chmouel @hrishin 

Signed-off-by: Vincent Demeester <vdemeest@redhat.com>

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [ :no_good_man: ] Includes [tests](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if functionality changed/added)
- [ :no_good_man: ] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)
- [x] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)

_See [the contribution guide](https://github.com/tektoncd/cli/blob/master/CONTRIBUTING.md)
for more details._

### CODE REVIEW

**Comment by chmouel** [comment]
look nice

**Comment by chmouel** [comment]
nice!

**Comment by vdemeester** [comment]
Example run : https://github.com/vdemeester/tektoncd-cli/releases/tag/v0.0.1 : the changelog is that way because of the tag being on a branch :angel:

**Comment by chmouel** [comment]
/lgtm

Really nice work!  🔥  Will test the arms binaries on a rpi

**Pull request merged**
