### PR TITLE
feat: display annotations for describe command

### PR DESCRIPTION
**Pull request by digglife**
# Changes

Display annotations for `describe` command. 
fixes: #1543

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [x] Includes [tests](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if functionality changed/added)
- [x] Run the code checkers with `make check`
- [x] Regenerate the manpages, docs and go formatting with `make generated`
- [x] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)

# Release Notes

```release-note
Display annotations for `describe` command.
```

### CODE REVIEW

**Comment by digglife** [comment]
rebased on main

**Comment by vinamra28** [comment]
@digglife, I guess some tests are failing. Can you please inspect?

**Comment by digglife** [comment]
Tests passed. It's a temporary glitch.

**Pull request merged**
