### PR TITLE
Use binary for building rpms

### PR DESCRIPTION
**Pull request by chmouel**
life is too short to care about compiling from source on multiple
rpm distros and multiple golang version.

not pretty at all tho... but better than nothing

built manually on copr : 

image

and tested in a contianer:

image

Signed-off-by: Chmouel Boudjnah <chmouel@redhat.com>

# Changes

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [ ] Includes [tests](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if functionality changed/added)
- [ ] Run the code checkers with `make check`
- [ ] Regenerate the manpages, docs and go formatting with `make generated`
- [ ] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)

_See [the contribution guide](https://github.com/tektoncd/cli/blob/master/CONTRIBUTING.md)
for more details._

# Release Notes

### CODE REVIEW

**Comment by piyush-garg** [comment]
/lgtm
cc @vdemeester @pradeepitm12

**Review by pradeepitm12 — APPROVED** [review]
/lgtm

**Comment by chmouel** [comment]
(those interactive tests are useless if flaky)

**Pull request merged**
