### PR TITLE
Use gotest.tool directly and not v3

### PR DESCRIPTION
**Pull request by chmouel**
We have failure when using v3 failing with older version of go not having a `go
mod`

```
pkg/cmd/pipelineresource/resource_testUtil.go:25:2: code in directory /Users/chmouel/GIT/go/src/github.com/tektoncd/cli/vendor/gotest.tools/v3/assert expects import "gotest.tools/assert"
```

do not use v3 directly in there

# Changes

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [ ] Includes [tests](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if functionality changed/added)
- [ ] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)
- [ ] Regenerate the manpages and docs with `make docs` and `make man` if needed.
- [ ] Run the code checkers with `make check`
- [ ] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)

_See [the contribution guide](https://github.com/tektoncd/cli/blob/master/CONTRIBUTING.md)
for more details._

# Release Notes

```
release-note
```

### CODE REVIEW

**Comment by piyush-garg** [comment]
I0203 19:28:45.683] /go/src/github.com/tektoncd/cli is out of date. Please run hack/update-codegen.sh

**Comment by chmouel** [comment]
@piyush-garg it seems that @vdemeester thinks we should really use gotest v3 for a reason, so i am going to 
/hold into this

**Comment by chmouel** [comment]
I swear update-codegen is not working for me!

**Pull request closed without merging**
