### PR TITLE
Update Task Tests from Test Builders to Structs

### PR DESCRIPTION
**Pull request by vinamra28**
# Changes

Migrating unit tests for `tkn task` from test builders to structs.

Part of #1145 

Signed-off-by: vinamra28 <vinjain@redhat.com>
# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [X] Includes [tests](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if functionality changed/added)
- [X] Run the code checkers with `make check`
- [X] Regenerate the manpages, docs and go formatting with `make generated`
- [X] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)

_See [the contribution guide](https://github.com/tektoncd/cli/blob/master/CONTRIBUTING.md)
for more details._

# Release Notes
```release-note
NONE
```

### CODE REVIEW

**Review by pradeepitm12 — COMMENTED** [review]
/lgtm

**Comment by chmouel** [comment]
/lgtm
/approve

🚀

**Pull request merged**
