### PR TITLE
Fix broken links in DEVELOPMENT.MD

### PR DESCRIPTION
**Pull request by hasanrashid**
This commit fixes broken links in under "To setup a cluster with GKE". The issue is described here: #1387

# Changes

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

-  #[ ] Includes [tests](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if functionality changed/added)
- [x] Run the code checkers with `make check`
- [x] Regenerate the manpages, docs and go formatting with `make generated`
- [x] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)

_See [the contribution guide](https://github.com/tektoncd/cli/blob/master/CONTRIBUTING.md)
for more details._

# Release Notes

### CODE REVIEW

**Comment by pradeepitm12** [comment]
ok-to-test

**Review by vdemeester — APPROVED** [review]

**Comment by pritidesai** [comment]
thanks @hasanrashid 

I verified the instructions match the ones in pipeline repo which were recently updated.

/lgtm

**Comment by vinamra28** [comment]
Thanks @pritidesai for verifying 🙏
/lgtm

**Pull request merged**
