### PR TITLE
Bumps Hub CLI Dependency

### PR DESCRIPTION
**Pull request by SM43**
This updates the hub dependency which adds new commands:
- info
- install task
- reinstall task
- upgrade task
- downgrade task

Signed-off-by: Shivam Mukhade <smukhade@redhat.com>

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [ ] Includes [tests](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if functionality changed/added)
- [x] Run the code checkers with `make check`
- [x] Regenerate the manpages, docs and go formatting with `make generated`
- [x] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)

_See [the contribution guide](https://github.com/tektoncd/cli/blob/master/CONTRIBUTING.md)
for more details._

# Release Notes

### CODE REVIEW

**Review by vdemeester — APPROVED** [review]

**Comment by piyush-garg** [comment]
@SM43 This does not seems to have a downgrade command

/hold

**Pull request merged**
