### PR TITLE
Remove unnecessary dependencies

### PR DESCRIPTION
**Pull request by shuheiktgw**
# Changes

Related this comment: https://github.com/tektoncd/cli/pull/134#discussion_r299275728

I simply ran `GO111MODULE=on go mod tidy` and removed unnecessary dependencies. Thanks! 👍 

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [x] Includes [tests](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if functionality changed/added)
- [x] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)
- [x] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)

_See [the contribution guide](https://github.com/tektoncd/cli/blob/master/CONTRIBUTING.md)
for more details._

### CODE REVIEW

**Comment by hrishin** [comment]
Thank you @shuheiktgw for the PR :+1: 

@vdemeester @chmouel could you review this dependency?

**Comment by vdemeester** [comment]
@hrishin https://github.com/golang/go/wiki/Modules#is-gosum-a-lock-file-why-does-gosum-include-information-for-module-versions-i-am-no-longer-using. `go.sum` just holds "reference hash" of what is or has been a dependency (a previous version, etc…). This is not a dependency, it's just a way to ensure reproductibility (and would fail if for some reason getting back to that version and the hash changed). I am fine letting those in or not. I didn't know `go mod tidy` would remove them, but that's fine by me :wink:

**Comment by chmouel** [comment]
yeah same, find by me,

**Pull request merged**
