### PR TITLE
Rename `tkn pipeline start` to `tkn pipeline run`

### PR DESCRIPTION
**Pull request by ImJasonH**
`start` remains an alias for `run` for users who had been using that.

Part of #524

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [x] Includes [tests](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if functionality changed/added)
- [x] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)
- [x] Regenerate the manpages and docs with `make docs` and `make man` if needed.
- [x] Run the code checkers with `make check`
- [x] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)

_See [the contribution guide](https://github.com/tektoncd/cli/blob/master/CONTRIBUTING.md)
for more details._

# Release Notes

```
Rename `tkn pipeline start` to `tkn pipeline run` -- with an alias to continue supporting `start`
```

### CODE REVIEW

**Comment by sthaha** [comment]
@ImJasonH would it better to just add `run` alias to the `start` command instead? If we did that instead of renaming `start` to `run` those script that depend on the `start` command need not change and we don't have to introduce a breaking change.

**Comment by chmouel** [comment]
I don't mind either (start or run) but as @sthaha suggested, i'd rather see an alias than a breaking change,

**Comment by vdemeester** [comment]
> @ImJasonH would it better to just add `run` alias to the `start` command instead? If we did that instead of renaming `start` to `run` those script that depend on the `start` command need not change and we don't have to introduce a breaking change.

There is an alias to `start` in the PR ([here](https://github.com/tektoncd/cli/pull/526/files#diff-3c87311eda1686abaaeba01f04ce8cbdR112)). A simplest change would be to keep the current `start.go` and add the `run` alias, the only thing then to "validate" is what should we generate for the documentation.

From https://github.com/tektoncd/cli/issues/524#issuecomment-566926653

> The question is then, which one should be the "documented" one, `run` or `start` ?  and which one is the alias. If we just want to be able to do `tkn task run`, then, an alias is enough. If we want "to move to `run`" (aka `man tkn-task-run`, and highlighting `run` instead of `start` in documentation), then a change making `start` becamo `run` (with an alias like #526 would be better). We can also enhance our doc/manpage generator to generate aliases commands to (aka for `tkn foo` that have a bar alias, generating `tkn-foo` and `tkn-bar` as manpage and cli reference doc).

**Comment by sthaha** [comment]
Sorry about the confusion .. totally missed that an Alias was added for `run` as `start`.

**Comment by vdemeester** [comment]
Actually, the more I think about that, the more I don't think `start` and `run` should be aliases, see https://github.com/tektoncd/cli/issues/524#issuecomment-566943727

**Comment by ImJasonH** [comment]
Lots of new design changes for this being discussed in https://github.com/tektoncd/cli/issues/524 -- closing until we reach agreement.

**Pull request closed without merging**
