### PR TITLE
add shorthand -a for --all flags

### PR DESCRIPTION
**Pull request by chmouel**
Added shorthand 'a' for the --all flag in various delete commands which has a --all to improve usability and consistency across the CLI and with kubectl.

This change affects the following commands:

- ClusterTriggerBinding delete
- EventListener delete
- Pipeline delete
- PipelineRun delete
- Task delete
- TaskRun delete
- TriggerBinding delete
- TriggerTemplate delete

# Changes

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [ ] Includes [tests](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if functionality changed/added)
- [ ] Run the code checkers with `make check`
- [ ] Regenerate the manpages, docs and go formatting with `make generated`
- [ ] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)

_See [the contribution guide](https://github.com/tektoncd/cli/blob/master/CONTRIBUTING.md)
for more details._

# Release Notes

 
```release-note
all commands with --all flag now has a a shorthand flag -a
```

### CODE REVIEW

**Comment by piyush-garg** [comment]
Hey @chmouel 

We were following here same like kubectl (1.30)

```
    --all=false:
	Delete all resources, in the namespace of the specified resource types.

    -A, --all-namespaces=false:
	If present, list the requested object(s) across all namespaces. Namespace in current context is ignored even
	if specified with --namespace.

```

In my opinion, `-a` short flag for `--all` does not add much value, but if @vdemeester @vinamra28 are fine, I am fine to get this in.

**Comment by vinamra28** [comment]
I agree with @piyush-garg, `--all` is already short 😅

**Comment by chmouel** [comment]
sounds good!

**Pull request closed without merging**
