### PR TITLE
Add all auth clients

### LINKED ISSUE #627: Missing OIDC support with Azure Active Directory
# Version and Operating System

**tkn Version:**
0.6.0

**Operating System:** 
macOS

# Expected Behavior
1) Have a k8s cluster where OIDC is enabled and using Azure AD: https://github.com/kubernetes/client-go/tree/master/plugin/pkg/client/auth/azure
2) use a kubeconfig with Azure AD enabled:

```
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: < cert>
    server: https://<my k8s apiserver>:6443
  name: my-cluster
contexts:
- context:
    cluster: my-cluster
    user: oidc
  name: my-cluster-system
current-context: my-cluster-system
kind: Config
preferences: {}
users:
- name: oidc
  user:
    auth-provider:
      config:
        access-token: <ey...>
        apiserver-id: <my apiserver id
        client-id: <my client id>
        environment: AzurePublicCloud
        expires-in: "3600"
        expires-on: "1561668931"
        refresh-token: <token>
        tenant-id: <my tenant id>
      name: azure
```
3) issue some tkn command, like 

> tkn pr list

and it works

# Actual Behavior
```
$ tkn pr list
Error: No Auth Provider found for name "azure"
```

# Steps to Reproduce the Problem

1.
2.
3.

# Additional Info

### PR DESCRIPTION
**Pull request by chmouel**
Add all auth client-go clients as documented here https://git.io/JvL6r

Closes #627

# Changes

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [ ] Includes [tests](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if functionality changed/added)
- [ ] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)
- [ ] Regenerate the manpages and docs with `make docs` and `make man` if needed.
- [ ] Run the code checkers with `make check`
- [ ] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)

_See [the contribution guide](https://github.com/tektoncd/cli/blob/master/CONTRIBUTING.md)
for more details._

# Release Notes

```
release-note
```

### CODE REVIEW

**Comment by chmouel** [comment]
Let me know if that works for you @tomhau01  

thanks!

**Comment by tomhau01** [comment]
Is there a binary somewhere I could test?

**Comment by chmouel** [comment]
@tomhau01 there is not on CI but i can provide you one, is that for osx, linux?

**Comment by chmouel** [comment]
Just saw that you are using OSX so here is a binary : 

https://osinstall.chmouel.com/tmp/tkn

**Comment by tomhau01** [comment]
Gave your binary a go, and it works. That was a very speedy fix, kudos!

**Comment by danielhelfand** [comment]
Build error is:

``` 
-* Gophercloud no longer returns an error when multiple endpoints are found. Instead, it will choose the first endpoint and discard the others [GH-1766](https://github.com/gophercloud/gophercloud/pull/1766)
```

**Comment by tomhau01** [comment]
No chance to get this into 0.7.0?

**Comment by chmouel** [comment]
@tomhau01 Sorry about this, I had some issues unfortunately with an unrelated (to azure) auth, let me try to rework this to only include the azure client.

I think it’s a bit late for 0.7.0 unfortunately as @piyush-garg is just finishing  the release

**Comment by tomhau01** [comment]
Okay, thanks for looking into it.

**Comment by chmouel** [comment]
@tomhau01 Hey Tom, i have fixed the CI issues and we are going to be able to roll this in for 0.7.1 (0.7.0 had some issues), out of sanity check can you test this binary to make sure everything is fine? https://osinstall.chmouel.com/tmp/tkn thansk!

**Comment by tomhau01** [comment]
Works fine!

**Comment by chmouel** [comment]
@tomhau01 cool thanks you,

@piyush-garg that's ready for merg for 0.7.1

**Pull request merged**
