### PR TITLE
Add pipelinerun watch command

### PR DESCRIPTION
**Pull request by chmouel**
# Changes

This will watch the pipelinerun and exit 1 if the pipelinerun has failed
or if there is an error getting the pipelinerun or exit 0 if it has
succeed.

This probably can be used nicely in scripting for example on linux using
the notify-send software :

tkn pr watch -L || notify-send -u=critical "Pipeline has failed" && notify-send "Pipeline has finished"

User can add a --showlog to implicitely show the log when watching.

The imp leverage on the exiting log command and catch the error
stream to detect  there is an error.

Screenshot: 

image

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [ ] Includes [tests](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if functionality changed/added)
- [X] Run the code checkers with `make check`
- [X] Regenerate the manpages, docs and go formatting with `make generated`
- [X] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)

_See [the contribution guide](https://github.com/tektoncd/cli/blob/master/CONTRIBUTING.md)
for more details._

# Release Notes

```release-note
add tkn pr watch to watch the execution of a pipelinerun and exit with the same status of the pipelinerun. This is most useful used with scripting on the shell piping the result to another binary (for example a notification software) 
```

### CODE REVIEW

**Comment by chmouel** [comment]
still need to upload the test but that's going more like a monday thing than a quick friday afternnon fun feature to code 😅

**Review by vdemeester — APPROVED** [review]
/retest

**Comment by chmouel** [comment]
/hold

need test and improvement, and basically reimp of https://github.com/chmouel/tkn-watch

**Comment by vdemeester** [comment]
@chmouel do you want to close this for now ?

**Comment by chmouel** [comment]
/close

sounds good!

**Pull request closed without merging**
