### PR TITLE
Bump tektoncd/pipelines v0.25.0, tektoncd/triggers v0.14.2 and tektoncd/hub cli latest

### LINKED ISSUE #1412: Bump pipelines to v0.25.0 and triggers v0.14.2 and hub cli to latest
Bump the vendor dependencies of tektoncd/pipeline v0.25.0 and tektoncd/triggers v0.14.2 and hub cli to latest

/assign

### PR DESCRIPTION
**Pull request by vinamra28**
# Changes

#### Bump tektoncd/pipelines to v0.25.0
- Add ConfigMap which can contain pipelines info and RBAC to access this ConfigMap which can be queried by CLI
- Graceful Pipeline Run Termination
- and many more
#### Bump tektoncd/triggers to v0.14.2
- Add Clusterrole Aggregate View and Edit for ClusterInterceptor CRD
#### Bump tektoncd/hub cli to latest
- Info and Get command now supports interactive mode
- Hub API server URL can be configured by setting the value of `HUB_API_SERVER` in `$HOME/.tekton/hub-config` file

closes #1412 

Signed-off-by: vinamra28 <vinjain@redhat.com>
# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [ ] Includes [tests](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if functionality changed/added)
- [ ] Run the code checkers with `make check`
- [ ] Regenerate the manpages, docs and go formatting with `make generated`
- [ ] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)

_See [the contribution guide](https://github.com/tektoncd/cli/blob/master/CONTRIBUTING.md)
for more details._

# Release Notes
```release-note
NONE
```

### CODE REVIEW

**Review by vdemeester — APPROVED** [review]

**Review by pradeepitm12 — APPROVED** [review]
/lgtm

**Pull request merged**
