### PR TITLE
Remove the rest of reference to Conditions 🥸

### PR DESCRIPTION
**Pull request by vdemeester**
# Changes

This is going to be required before we bump the pipeline version where
the code has been removed.

Signed-off-by: Vincent Demeester <vdemeest@redhat.com>

/kind misc
/cc @tektoncd/cli-maintainers @abayer 

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [ ] Includes [tests](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if functionality changed/added)
- [x] Run the code checkers with `make check`
- [x] Regenerate the manpages, docs and go formatting with `make generated`
- [x] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)

_See [the contribution guide](https://github.com/tektoncd/cli/blob/master/CONTRIBUTING.md)
for more details._

# Release Notes

```release-note
NONE
```

### CODE REVIEW

**Comment by vdemeester** [comment]
/hold
I think I have a few more to remove still

**Review by vinamra28 — COMMENTED** [review]
/lgtm

**Review by pradeepitm12 — APPROVED** [review]
>/lgtm

**Pull request merged**
