### PR TITLE
Add information in README on how to install on Arch

### PR DESCRIPTION
**Pull request by chmouel**
# Changes

Add information about arch package install.
Add release process information on how to let the arch packager know
that the arch package is outdated.

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [X] Includes [tests](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if functionality changed/added)
- [X] Run the code checkers with `make check`
- [X] Regenerate the manpages, docs and go formatting with `make generated`
- [X] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)

_See [the contribution guide](https://github.com/tektoncd/cli/blob/master/CONTRIBUTING.md)
for more details._

# Release Notes

```release-note
Add information about Arch package
```

### CODE REVIEW

**Review by vinamra28 — COMMENTED** [review]
/lgtm

**Comment by chmouel** [comment]
@vdemeester  any chance to get a merge on this ?

(i use arch btw)

**Comment by jbpratt** [comment]
cc @shibumi :cat:

**Comment by shibumi** [comment]
Looks good :D also the note about messaging the packager. Normally I get notified when the tekton-cli package gets updated, but sometimes I am drowning in GitHub notifications and might miss this.

**Review by shibumi — APPROVED** [review]

**Pull request merged**
