### PR TITLE
RFC: Adds a subcommand to output pipeline as DOT graph

### PR DESCRIPTION
**Pull request by bkmeneguello**
# Changes

I'm adding support for DOT graph generation to describe Pipeline (and PipelineRun soon)

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [ ] Includes [tests](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if functionality changed/added)
- [ ] Run the code checkers with `make check`
- [ ] Regenerate the manpages, docs and go formatting with `make generated`
- [ ] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)

_See [the contribution guide](https://github.com/tektoncd/cli/blob/master/CONTRIBUTING.md)
for more details._

# Release Notes

```
Support for Pipeline graph generation
```

### CODE REVIEW

**Comment by bkmeneguello** [comment]
I'll wait for feedback to further add PipelineRun graph command and required man pages and stuff.

**Comment by bkmeneguello** [comment]
This command generate this output, for example:
```
digraph {
  graph [rankdir=TB];
  node [shape=box];
  "<start>" [label=start,shape=diamond];
  "a";
  "<start>" -> "a";
  "b";
  "<start>" -> "b";
  "c";
  "<start>" -> "c";
  "d";
  "<start>" -> "d";
  "e";
  "<start>" -> "e";
  "f";
  "<start>" -> "f";
  "g";
  "<start>" -> "g";
  "h";
  "g" -> "h";
  "a" -> "h";
  "b" -> "h";
  "c" -> "h";
  "d" -> "h";
  "e" -> "h";
  "f" -> "h";
  i;
  "h" -> "i";
  "j";
  "h" -> "j"
  "i" -> "j";
}
```
which renders to:
pipeline

**Comment by danielhelfand** [comment]
@bkmeneguello Thanks so much for submitting this idea! I think this is really great and could also be worthwhile for PipelineRuns as well as you mention. I'll give this a try out, but this may be worth discussing in our weekly working group. We would love for you to present it, but we can also discuss as a group and provide feedback if that's easier.

**Comment by bkmeneguello** [comment]
Sure @danielhelfand, I can join with you to discuss the ideas. Just send me the invite pls.

**Comment by danielhelfand** [comment]
https://github.com/tektoncd/community/blob/master/working-groups.md#cli

**Pull request closed without merging**
