### PR TITLE
Hide sections with empty results for `describe` command

### PR DESCRIPTION
**Pull request by digglife**
# Changes

Hide sections with empty results for `describe` command.

Issue: #790 

Previous:

```bash
$ tkn task describe hello 
Name:        hello
Namespace:   default

📨 Input Resources

 No input resources

📡 Output Resources

 No output resources

⚓ Params

 No params

📝 Results

 No results

📂 Workspaces

 No workspaces

🦶 Steps

 ∙ hello

🗂  Taskruns

NAME              STARTED        DURATION     STATUS
hello-run-fs65c   20 hours ago   24 seconds   Failed
```

Now:
```bash
$ tkn task describe hello 
Name:        hello
Namespace:   default

🦶 Steps

 ∙ hello

🗂  Taskruns

NAME              STARTED        DURATION     STATUS
hello-run-fs65c   20 hours ago   24 seconds   Failed
```

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [x] Includes [tests](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if functionality changed/added)
- [x] Run the code checkers with `make check`
- [x] Regenerate the manpages, docs and go formatting with `make generated`
- [x] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)

# Release Notes

```release-note
Hide the sections with empty results for `describe` command.
```

### CODE REVIEW

**Review by vinamra28 — COMMENTED** [review]
/ok-to-test
/lgtm

**Comment by digglife** [comment]
There was a E2E test for `pipeline describe` failed and I fixed it. Please review. Thanks!

**Review by pradeepitm12 — COMMENTED** [review]
/lgtm

**Review by vdemeester — APPROVED** [review]

**Comment by digglife** [comment]
I don't know where this `TestPipelineRunDescribe_cancelled_pipelinerun_multiple_taskrun` comes from...
I remember that the tests passed last time.

**Comment by vinamra28** [comment]
@digglife can you please try to rebase over upstream/main and see if that fixes the CI?

**Comment by digglife** [comment]
@vinamra28 Thanks for the hint. `TestPipelineRunDescribe_cancelled_pipelinerun_multiple_taskrun` was added to `pkg/cmd/pipelinerun/describe_test.go` recently. I rebased the commit on the main branch and fixed the test. Now we need LGTM again... :)

**Pull request merged**
