### PR TITLE
Add timestamps flags to all pipeline resources that have logs command

### PR DESCRIPTION
**Pull request by seongpyoHong**
# Changes
Related PR: https://github.com/tektoncd/cli/pull/1751
Add timestamps flags to all pipeline resources(`clusterTask`, `Task`, `Pipeline`, `TaskRun`) that have logs command.

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [ ] Includes [tests](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if functionality changed/added)
- [x] Run the code checkers with `make check`
- [x] Regenerate the manpages, docs and go formatting with `make generated`
- [x] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)

_See [the contribution guide](https://github.com/tektoncd/cli/blob/master/CONTRIBUTING.md)
for more details._

# Release Notes
```release-note
Add timestamps flags to all pipeline resources that have logs command.
```

### CODE REVIEW

**Comment by piyush-garg** [comment]
PipelineRun also have logs commands

**Review by vinamra28 — APPROVED** [review]
thanks for the patch 👍🏻

**Pull request merged**
