### PR TITLE
Bump chains to 0.9.0

### PR DESCRIPTION
**Pull request by concaf**
# Changes

Bumps Chains version to 0.9.0

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [x] Includes [tests](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if functionality changed/added)
- [x] Run the code checkers with `make check`
- [x] Regenerate the manpages, docs and go formatting with `make generated`
- [x] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)

_See [the contribution guide](https://github.com/tektoncd/cli/blob/master/CONTRIBUTING.md)
for more details._

# Release Notes

```release-note
NONE
```

### CODE REVIEW

**Comment by concaf** [comment]
/assign @pradeepitm12 @piyush-garg 
I've pushed 2 commits in this PR, one for updating `go.sum`, `go.mod` and another for the vendor update so it becomes easier to review in the web UI 😅

**Comment by concaf** [comment]
will wait for #1570 to be merged so I can base this on top of that

**Comment by pradeepitm12** [comment]
@concaf https://github.com/tektoncd/cli/pull/1570 is merged now

**Comment by concaf** [comment]
Replaced by #1580

**Pull request closed without merging**
