### PR TITLE
Remove conditions from README

### PR DESCRIPTION
**Pull request by chmouel**
since it has been removed the link checker bug us in CI,

```
----------------------------------------------
---- Checking links in the markdown files ----
----------------------------------------------
README.md
	ERROR	docs/cmd/tkn_condition.md
		Stat docs/cmd/tkn_condition.md: no such file or directory
--------------------------------
```

Signed-off-by: Chmouel Boudjnah <chmouel@redhat.com>

# Changes

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [ ] Includes [tests](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if functionality changed/added)
- [ ] Run the code checkers with `make check`
- [ ] Regenerate the manpages, docs and go formatting with `make generated`
- [ ] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)

_See [the contribution guide](https://github.com/tektoncd/cli/blob/master/CONTRIBUTING.md)
for more details._

# Release Notes

```release-note
NONE
```

### CODE REVIEW

**Review by pradeepitm12 — APPROVED** [review]
/lgtm

**Comment by chmouel** [comment]
PSA: a CI that fails 8 out 10 is really not worth it...

(should probably be a tweet instead of a github comment)

**Comment by piyush-garg** [comment]
e2e are fixed with https://github.com/tektoncd/cli/pull/1629

**Pull request merged**
