### PR TITLE
minor: whitespace cleanup

### PR DESCRIPTION
**Pull request by sthaha**
# Changes
Minor change to fix trailing whitespaces in README.md

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [❌ ] Includes [tests](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if functionality changed/added)
- [❌  ] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)
- [x] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)

_See [the contribution guide](https://github.com/tektoncd/cli/blob/master/CONTRIBUTING.md)
for more details._

# Release Notes

```
release-note
```

### CODE REVIEW

**Comment by sthaha** [comment]
Also, I wanted to check if the `CLA` check is fine since in other PRs where I added a commit on top, the bot complain that I hadn't signed it 🤷‍♂

**Comment by chmouel** [comment]
@sthaha i think some people are commiting with their personal email and that's why cla is not validated : 

```git
[IncludeIF "gitdir/i:~/GIT/go/src/github.com/tektoncd/"]
	path = ~/.gitconfig.redhat
```

and ~/.gitconfig.redhat : 

```git
[user]
	email = MYEMAIL@redhat.com
```

@piyush-garg @hrishin please adjust your config (and the path /email in there)

**Comment by hrishin** [comment]
@chmouel configured it, thanks! :+1: 

```
~/.gitconfig
[includeIf "gitdir:/home/hshinde/go/src/github.com/tektoncd"]
    path = /home/hshinde/.config/git/config.d/redhat.gitconfig
```
```
12:39 $ cat /home/hshinde/.config/git/config.d/redhat.gitconfig 
[user]
  name  = Hrishikesh Shinde
  email = hshinde@redhat.com
```

**Pull request merged**
