### PR TITLE
Start doing testing against pipeline release nightly

### LINKED ISSUE #496: Start doing testing against nightly
We are currently testing only against the stable version of pipeline.

When there is breaking change in pipeline, we rush it to get it fixed like
mad(wo)men to fix the CI.

Let's do two different jobs, one against nightly and one against stable version
of pipeline.

/area testing
/kind feature

/cc @vdemeester @hrishin @sthaha @danielhelfand

### PR DESCRIPTION
**Pull request by chmouel**
Let's use nightly pipeline release.yaml, if we could not find it (i.e: nightly
pipeline as failed) let's fallback to the released version

Closes #496

### CODE REVIEW

**Comment by chmouel** [comment]
agreeed, but i have no idea how to do that :-)

**Comment by vdemeester** [comment]
@chmouel no worries, we could do it using `prow` but I feel we can wait for `tektoncd/cli` CI using tekton :angel:

**Comment by chmouel** [comment]
that works is only for midstream testing, we haven't done anything on upstream tekton-on-tekton  🏎 🍝 🐏 🌮 🏈 ⚽️

**Comment by vdemeester** [comment]
> that works is only for midstream testing, we haven't done anything on upstream tekton-on-tekton , so that going to take quite quite some time stuck_out_tongue racing_car spaghetti ram taco football soccer

@chmouel What do you mean, we are starting to work on that too upstream :angel: :wink:

**Comment by chmouel** [comment]
awesome, so then let's wait for that, i understand better how to update tekton tasks than prow jobs 🤣

**Comment by chmouel** [comment]
Thinking about it, we could on the meantime rerun twice the tests, with different release (if we uninstall pipeline between runs)...

**Comment by chmouel** [comment]
I think this is still mergeable!

**Pull request merged**
