### PR TITLE
Bump golangci-lint to v1.54.2

### PR DESCRIPTION
**Pull request by vinamra28**
# Changes

Fixes couple of lint issues:
- G101: Potential hardcoded credentials
- G601: Implicit memory aliasing in for loop.

Temporarily disabling:
- G602: Potentially accessing slice out of bounds as this is a known
  false positive and can be tracked at https://github.com/securego/gosec/issues/1005

Also bump golangci-lint version in release pipeline

Signed-off-by: vinamra28 <jvinamra776@gmail.com>

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [NA] Includes [tests](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if functionality changed/added)
- [X] Run the code checkers with `make check`
- [X] Regenerate the manpages, docs and go formatting with `make generated`
- [X] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)

_See [the contribution guide](https://github.com/tektoncd/cli/blob/master/CONTRIBUTING.md)
for more details._

# Release Notes
```release-note
NONE
```

### CODE REVIEW

**Comment by piyush-garg** [comment]
can we please do the change in release pipeline too

**Comment by chmouel** [comment]
/lgtm

maybe take the opportunity to add more linters !  (we have a few of them in [PaaC](https://github.com/openshift-pipelines/pipelines-as-code/blob/main/.golangci.yml#L23))

**Comment by vinamra28** [comment]
> /lgtm
> 
> maybe take the opportunity to add more linters ! (we have a few of them in [PaaC](https://github.com/openshift-pipelines/pipelines-as-code/blob/main/.golangci.yml#L23))

sure @chmouel, probably can take this as next step

**Pull request merged**
