### PR TITLE
Add delete all flag to task command

### PR DESCRIPTION
**Pull request by 16yuki0702**
# Changes
Add delete all flag to the task command feature for https://github.com/tektoncd/cli/issues/233
(related to https://github.com/tektoncd/cli/pull/256)

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [ ] Includes [tests](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if functionality changed/added)
- [ ] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)
- [ ] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)

_See [the contribution guide](https://github.com/tektoncd/cli/blob/master/CONTRIBUTING.md)
for more details._

# Release Notes

```
you can specify delete all flag when using task command.
```

### CODE REVIEW

**Comment by chmouel** [comment]
@16yuki0702  we need to fix https://github.com/tektoncd/cli/issues/259 first,

**Comment by 16yuki0702** [comment]
@chmouel 
> @16yuki0702 we need to fix #259 first,

oh... I see, thanks!!

**Pull request merged**
