### PR TITLE
Fix nil pointer error

### PR DESCRIPTION
**Pull request by khrm**
# Changes
Fix nil pointer exception while running taskrun or pipelinerun list

Fixes https://github.com/tektoncd/cli/issues/204 and https://github.com/tektoncd/cli/issues/202

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [x] Includes [tests](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if functionality changed/added)
- [x] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)
- [x] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)

_See [the contribution guide](https://github.com/tektoncd/cli/blob/master/CONTRIBUTING.md)
for more details._

# Release Notes

```
release-note
```

### CODE REVIEW

**Comment by khrm** [comment]
@vdemeester @hrishin This is done.

**Comment by danielhelfand** [comment]
Out of curiosity, under what conditions would Status.StartTime be nil when running a watch? It would be my expectation that Status.StartTime should always have one?

**Comment by vdemeester** [comment]
@danielhelfand if the API calls (from the cli) happens before the controller updating the PipelineRun. The window of this happening is small, but it does exists :angel:

**Comment by danielhelfand** [comment]
@vdemeester Gotcha, thanks!

**Pull request merged**
