### PR TITLE
Add support for a `--build-cross-tests` flag in presubmit

### PR DESCRIPTION
**Pull request by vdemeester**
# Changes

This will be used by the prow job responsible for doing the cross
build job.

Signed-off-by: Vincent Demeester <vdemeest@redhat.com>

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [ ] Includes [tests](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if functionality changed/added)
- [ ] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)
- [x] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)

_See [the contribution guide](https://github.com/tektoncd/cli/blob/master/CONTRIBUTING.md)
for more details._

### CODE REVIEW

**Comment by hrishin** [comment]
/lgtm 

@sthaha could you?

**Comment by sthaha** [comment]
@vdemeester why does it have should-not-merge label?

**Pull request merged**
