### PR TITLE
update go build and test

### PR DESCRIPTION
**Pull request by pradeepitm12**
update go build and test to 1.16.13

Signed-off-by: Pradeep Kumar <pradkuma@redhat.com>

# Changes

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [ ] Includes [tests](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if functionality changed/added)
- [ ] Run the code checkers with `make check`
- [ ] Regenerate the manpages, docs and go formatting with `make generated`
- [ ] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)

_See [the contribution guide](https://github.com/tektoncd/cli/blob/master/CONTRIBUTING.md)
for more details._

# Release Notes

### CODE REVIEW

**Comment by pradeepitm12** [comment]
A try to fix build and test tasks. 
should we update to 1.16.0?

**Comment by piyush-garg** [comment]
yes we should as we did https://github.com/tektoncd/cli/blob/main/go.mod#L3

**Review by vinamra28 — COMMENTED** [review]
/lgtm

**Review by vdemeester — APPROVED** [review]

**Pull request merged**
