### PR TITLE
Add direnv support with boilerplate

### PR DESCRIPTION
**Pull request by vdemeester**
# Changes

This add a .envrc file that will be used by direnv to setup the environment for the project if `direnv` is enabled. It also adds a `.env.sample` to give an example of what it could be useful for. And it adds `.env` to gitignore to make sure people do not commit their specific environment configurations.

/cc @tektoncd/cli-maintainers 

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [ ] Includes [tests](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if functionality changed/added)
- [ ] Run the code checkers with `make check`
- [ ] Regenerate the manpages, docs and go formatting with `make generated`
- [x] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)

_See [the contribution guide](https://github.com/tektoncd/cli/blob/master/CONTRIBUTING.md)
for more details._

# Release Notes

```release-note
NONE
```

### CODE REVIEW

**Comment by chmouel** [comment]
I already have a .envrc for some of my specific things on cli, and why this needs to be in repo ?

**Comment by chmouel** [comment]
what kind of shared task do you have in mind?

isn't pre-commit something more appropriate if it's lint/checks/code related?

**Comment by vdemeester** [comment]
@chmouel for example, https://github.com/tektoncd/cli/pull/2176

**Comment by chmouel** [comment]
We discussed this a bit offline and it's probably a bad idea for security (since it bypass the `direnv allow` model) and make it a bit awkward for folks that already have their own .envrc

**Pull request closed without merging**
