### PR TITLE
ROADMAP.md: update it to reflect 2022 goals

### PR DESCRIPTION
**Pull request by vdemeester**
# Changes

Just a "quick" update on the ROADMAP. Feel free to comment if I am missing something. We can also always follow-up during the year to add/remove items 😉 

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [ ] Includes [tests](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if functionality changed/added)
- [x] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)
- [x] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)

_See [the contribution guide](https://github.com/tektoncd/operator/blob/master/CONTRIBUTING.md) for more details._

# Release Notes

```release-note
NONE
```

### CODE REVIEW

**Review by pradeepitm12 — APPROVED** [review]
> lgtm

**Review by vinamra28 — COMMENTED** [review]
lgtm

**Review by vinamra28 — APPROVED** [review]
lgtm

**Review by pradeepitm12 — APPROVED** [review]
/lgtm

**Pull request merged**
