### PR TITLE
Bump golangci-lint to v1.47.2 for Go 1.18 support

### PR DESCRIPTION
**Pull request by abayer**
# Changes

We're moving the `test-runner` image to Go 1.18.3, and that means we need a newer version of `golangci-lint` or it'll spit out false positives all over the place.

/kind misc

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [ ] Includes [tests](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if functionality changed/added)
- [x] Run the code checkers with `make check`
- [ ] Regenerate the manpages, docs and go formatting with `make generated`
- [x] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)

_See [the contribution guide](https://github.com/tektoncd/cli/blob/master/CONTRIBUTING.md)
for more details._

# Release Notes

```release-note
NONE
```

### CODE REVIEW

**Comment by abayer** [comment]
cc @tektoncd/cli-maintainers

**Review by pradeepitm12 — COMMENTED** [review]
/lgtm

**Pull request merged**
