### PR TITLE
grouped commands into logical groups for cli usage and help

### LINKED ISSUE #179: Group commands in help message
The help message should group the commands into logical groups and order of relevance:

Current behavior:
```
$ tkn --help

Available Commands:
  clustertask Manage clustertasks
  completion  Prints shell completion scripts
  help        Help about any command
  pipeline    Manage pipelines
  pipelinerun Manage pipelineruns
  resource    Manage pipeline resources
  task        Manage tasks
  taskrun     Manage taskruns
  version     Prints version information
```

Expected behavior:
```
Available Commands:
  clustertask Manage clustertasks
  task        Manage tasks
  pipeline    Manage pipelines
  pipelinerun Manage pipelineruns
  taskrun     Manage taskruns
  resource    Manage pipeline resources

  completion  Prints shell completion scripts
  help        Help about any command
  version     Prints version information
```

### PR DESCRIPTION
**Pull request by girishramnani**
# Changes
Created two groups - "main" and "utility" using annotation (key: "commandType"). Used the annotation in the usage template to format accordingly.
Fixes #179 

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [ ] Includes [tests](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if functionality changed/added)
- [ ] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)
- [X] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)

_See [the contribution guide](https://github.com/tektoncd/cli/blob/master/CONTRIBUTING.md)
for more details._

# Release Notes

```
The cli help and usage now have logical grouping of commands
```

### CODE REVIEW

**Comment by siamaksade** [comment]
@girishramnani thanks for the PR. Could we also give a title to the groupings. Here is an example with updated descriptions for the commands:

```
CLI for tekton pipelines

Usage:
  tkn [command] [flags]

Pipeline Commands:
  clustertask Manage clustertasks
  pipeline    Manage pipelines
  pipelinerun Manage pipelineruns
  resource    Manage pipeline resources
  task        Manage tasks
  taskrun     Manage taskruns

Other Commands:
  completion  Prints shell completion code for the specified shell (bash or zsh)
  version     Prints the client version information

Flags:
  -h, --help   help for tkn

Use "tkn <command> --help" for more information about available sub-commands
```

**Comment by girishramnani** [comment]
sure @siamaksade

**Comment by girishramnani** [comment]
@siamaksade I rebased my PR and also did the necessary change.
This is how it looks like right now
```
CLI for tekton pipelines

Usage:
tkn [command]

Available Commands:
clustertask Manage clustertasks
pipeline    Manage pipelines
pipelinerun Manage pipelineruns
resource    Manage pipeline resources
task        Manage tasks
taskrun     Manage taskruns

Other Commands:
completion  Prints shell completion scripts
help        Help about any command
version     Prints version information

Flags:
  -h, --help   help for tkn

Use "tkn [command] --help" for more information about a command.```

**Comment by girishramnani** [comment]
so the cli now finally gives this as usage 
```
[gramnani@girish cli]$ ./tkn 
CLI for tekton pipelines

Usage:
tkn [command] [options]

Available Commands:
clustertask Manage clustertasks
pipeline    Manage pipelines
pipelinerun Manage pipelineruns
resource    Manage pipeline resources
task        Manage tasks
taskrun     Manage taskruns

Other Commands:
completion  Prints shell completion scripts
version     Prints version information

Flags:
  -h, --help   help for tkn

Use "tkn [command] --help" for more information about a command.```

**Comment by siamaksade** [comment]
@hrishin ah you are right! @girishramnani added it because I asked 🙈

**Comment by girishramnani** [comment]
removing

**Comment by girishramnani** [comment]
removed @hrishin @siamaksade

**Comment by hrishin** [comment]
Thank you @sthaha, @siamaksade  :+1: 

@vdemeester do you mean? 

```
Usage:
   tkn [command] [options]
```

**Comment by vdemeester** [comment]
> @vdemeester do you mean?
> 
> ```
> Usage:
>    tkn [command] 
> ```

@hrishin nope :angel: I mean as I put it before, or 

```
CLI for tekton pipelines

Usage: tkn [command] [options]

Available Commands:
  clustertask Manage clustertasks
  pipeline    Manage pipelines
  pipelinerun Manage pipelineruns
  resource    Manage pipeline resources
  task        Manage tasks
  taskrun     Manage taskruns

Other Commands:
  completion  Prints shell completion scripts
  version     Prints version information

Flags:
  -h, --help   help for tkn

Use "tkn [command] --help" for more information about a command.
```

It's not indented currently when I compile this PR :angel:

**Comment by girishramnani** [comment]
So I can do the indent but still confused if we need to add the `[options]` @vdemeester

**Comment by girishramnani** [comment]
@vdemeester added indent as mentioned above

**Pull request merged**
