### PR TITLE
tests: import pipeline internal builders 🏒

### LINKED ISSUE #1145: Move from pipeline builders to structs
Right now, in CLI unit tests and probably e2e test also, pipeline builders are getting used to create test data. Pipeline builders have been marked deprecated and now with the merge of PR https://github.com/tektoncd/pipeline/pull/3124 they will get removed.

As it happens and we bump the pipeline dependency in CLI to that pipeline version, it may break all our tests. Possible solutions to go forward is
 - Modify all the tests to use structs rather than the builders.
 - Copy the builders(which are in internal pkg) to CLI codebase from vendor and use (Maybe a workaround )

Creating this issue so that we can keep track and do the needful.

### PR DESCRIPTION
**Pull request by vdemeester**
# Changes

Importing pipeline internal builders in cli so that we can safely take
time to migrate out of them with less pressure (and with less
dependency problems).

This doesn't prevent to fix #1145, it's just putting less pressure on getting it done before the next release :wink: 

Signed-off-by: Vincent Demeester <vdemeest@redhat.com>

/cc @piyush-garg @danielhelfand @pradeepitm12 

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [x] Includes [tests](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if functionality changed/added)
- [x] Run the code checkers with `make check`
- [x] Regenerate the manpages, docs and go formatting with `make generated`
- [x] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)

_See [the contribution guide](https://github.com/tektoncd/cli/blob/master/CONTRIBUTING.md)
for more details._

/kind misc

### CODE REVIEW

**Comment by piyush-garg** [comment]
/lgtm

One question, are these builders from 1.16?

**Comment by vdemeester** [comment]
> /lgtm
> 
> One question, are these builders from 1.16?

0.15.2 (because they were removed before 0.16.0)

**Comment by piyush-garg** [comment]
> > /lgtm
> > One question, are these builders from 1.16?
> 
> 0.15.2 (because they were removed before 0.16.0)

But the internal is there in 0.16 right? Thet are removed from test/builder pkg

**Review by pradeepitm12 — COMMENTED** [review]
/lgtm

**Comment by vdemeester** [comment]
> > > /lgtm
> > > One question, are these builders from 1.16?
> > 
> > 
> > 0.15.2 (because they were removed before 0.16.0)
> 
> But the internal is there in 0.16 right? They are removed from test/builder pkg

yeah it's there lol, that's a good point. I can bump it to 0.16.0 if needed in a follow-up :stuck_out_tongue_closed_eyes:

**Review by danielhelfand — APPROVED** [review]
/lgtm

We should also announce in release notes for v0.13.0 that users should not develop around these test builders as they will not be supported long term. But think it makes sense to add these for the time being to more gracefully move away from them.

**Comment by piyush-garg** [comment]
> /lgtm
> 
> We should also announce in release notes for v0.13.0 that users should not develop around these test builders as they will not be supported long term. But think it makes sense to add these for the time being to more gracefully move away from them.

I don't think people are using anything from CLI to use builders.

**Comment by danielhelfand** [comment]
Yeah, from #1168.

**Comment by vdemeester** [comment]
Rebased :wink: :angel: :upside_down_face:

**Pull request merged**
