### PR TITLE
Uncapitalize error strings

### LINKED ISSUE #248: Uncapitalize error messages
As per https://github.com/golang/go/wiki/CodeReviewComments#error-strings

```
% git grep fmt.Errorf\(\"[A-Z] pkg
pkg/cmd/pipeline/delete.go:74:          return fmt.Errorf("Failed to create tekton client")
pkg/cmd/pipeline/delete.go:78:          return fmt.Errorf("Failed to delete pipeline %q: %s", pName, err)
pkg/cmd/pipeline/delete.go:97:                  return fmt.Errorf("Canceled deleting pipeline %q", pName)
pkg/cmd/pipeline/logs.go:308:           return "", fmt.Errorf("No pipeline runs found for %s in namespace: %s", pName, ns)
pkg/cmd/pipeline/start.go:259:          return nil, fmt.Errorf("No pipelineruns found in namespace: %s", ns)
pkg/cmd/pipelineresource/delete.go:60:          return fmt.Errorf("Failed to create tekton client")
pkg/cmd/pipelineresource/delete.go:64:          return fmt.Errorf("Failed to delete pipelineresource %q: %s", preName, err)
pkg/cmd/pipelineresource/describe.go:90:                return fmt.Errorf("Failed to create tekton client")
pkg/cmd/pipelineresource/describe.go:95:                return fmt.Errorf("Failed to find pipelineresource %q", preName)
pkg/cmd/pipelineresource/list.go:75:                            return fmt.Errorf("Failed to list pipelineresources. Invalid resource type %s", opts.Ty
pkg/cmd/pipelinerun/cancel.go:45:               return fmt.Errorf("Failed to create tekton client")
pkg/cmd/pipelinerun/cancel.go:50:               return fmt.Errorf("Failed to find pipelinerun: %s", prName)
pkg/cmd/pipelinerun/cancel.go:56:               return fmt.Errorf("Failed to cancel pipelinerun: %s, err: %s", prName, err.Error())
pkg/cmd/pipelinerun/describe.go:122:            return fmt.Errorf("Failed to create tekton client")
pkg/cmd/pipelinerun/describe.go:127:            return fmt.Errorf("Failed to find pipelinerun %q", prName)
pkg/helper/pods/fake/stream.go:49:      return nil, fmt.Errorf("Failed to stream container logs")
```

### PR DESCRIPTION
**Pull request by gavinfish**
# Changes

Uncapitalize error strings to resolve #248.

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [ ] Includes [tests](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if functionality changed/added)
- [ ] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)
- [X] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)

_See [the contribution guide](https://github.com/tektoncd/cli/blob/master/CONTRIBUTING.md)
for more details._

# Release Notes

```
n/a
```

### CODE REVIEW

**Comment by chmouel** [comment]
I think golangci should have a way to enforce those, we need to find a way to enable it in .golangci.yaml

**Comment by sthaha** [comment]
@gavinfish thanks for the PR 🤗 . I wanted to merge this PR but for the merge conflict. Could you please resolve and resubmit?

**Comment by gavinfish** [comment]
@chmouel  I think we need to update the thrift location in go.sum, FYI https://thrift.apache.org/lib/go

**Comment by chmouel** [comment]
nice one thanks, will do an update of the modules

**Comment by vdemeester** [comment]
@gavinfish needs a rebase :angel: 
/lgtm cancel
(to unblock tide)

**Pull request merged**
