### PR TITLE
Add section of Skipped tasks in tkn pr describe

### PR DESCRIPTION
**Pull request by vinamra28**
# Changes

Since when expressions are now supported in Tekton Pipelines for
guarding the execution of `Pipeline` so a new section of Skipped Tasks
is introduced which will display the list of all Skipped Tasks which
did not satisfy the conditions specified in when expressions.

Part of #1222 

Signed-off-by: vinamra28 <vinjain@redhat.com>
# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [X] Includes [tests](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if functionality changed/added)
- [X] Run the code checkers with `make check`
- [X] Regenerate the manpages, docs and go formatting with `make generated`
- [X] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)

_See [the contribution guide](https://github.com/tektoncd/cli/blob/master/CONTRIBUTING.md)
for more details._

# Release Notes
```release-note
Display list of Skipped Tasks in tkn pr describe command which we get when the conditions in when expressions are not met
```

### CODE REVIEW

**Review by vdemeester — APPROVED** [review]

**Review by pradeepitm12 — APPROVED** [review]
/lgtm

**Pull request merged**
