### PR TITLE
`tkn version` reflects pipeline version

### LINKED ISSUE #463: Feature Request: tkn pipeline version
# Expected Behavior
tkn pipeline version
pipeline version : v0.8.0
or 
tkn version
 Client version: 0.5.0
 Server version:  0.8.0
# Actual Behavior
N/A
or 
tkn version 
Client version: 0.5.0

# Additional Info

### PR DESCRIPTION
**Pull request by waveywaves**
fixes https://github.com/tektoncd/cli/issues/463

# Changes

- This PR will have to wait for being merged till the next release for pipline happens I suppose.
- fixes #463 

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [ ] Includes [tests](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if functionality changed/added)
- [ ] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)
- [ ] Regenerate the manpages and docs with `make docs` and `make man` if needed.
- [ ] Run the code checkers with `make check`
- [ ] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)

_See [the contribution guide](https://github.com/tektoncd/cli/blob/master/CONTRIBUTING.md)
for more details._

# Release Notes

```
release-note
```

### CODE REVIEW

**Comment by vdemeester** [comment]
As @chmouel said, it's gonna be misleading and will always be `-dev` as this is using it as library. To get the version from the server, we need to query it :angel:

**Comment by waveywaves** [comment]
@vdemeester @chmouel Yeah that makes sense. It would make more sense to have the version to be exposed via the API or on a label in a namespace becuase it will pick up dev :/ I will try that out instead.

**Comment by chmouel** [comment]
maybe i am wrong but i don't think there is a way to do with CRDs?

**Comment by vdemeester** [comment]
> maybe i am wrong but i don't think there is a way to do with CRDs?

So far, nope :sweat:

**Comment by hrishin** [comment]
@waveywaves @chmouel @vdemeester how about adding one more end point in pipelines `/version`, just like it has `/metrics` end point?

**Comment by vdemeester** [comment]
> @waveywaves @chmouel @vdemeester how about adding one more end point in pipelines `/version`, just like it has `/metrics` end point?

It could work indeed :angel: might required some changes in `knative/pkg` :angel:

**Comment by chmouel** [comment]
Are you updating this @waveywaves ?

**Comment by waveywaves** [comment]
@chmouel Yes I will be updating it right away !

**Pull request closed without merging**
