### PR TITLE
Bump tektoncd/pipeline to v0.44.0 and remove cluster and cloudevent pipelineresource

### PR DESCRIPTION
**Pull request by piyush-garg**
Bump tektoncd/pipeline to v0.44.0

Remove cluster and cloudevent pipelineresource
This removes the functionality related to cluster and cloudevent
pipelineresource from cli like ct, t and p start cmd

Also pr create will not support cloudevent and cluster resource

Update tests accordingly.

Part of #1657 

# Changes

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [x] Includes [tests](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if functionality changed/added)
- [x] Run the code checkers with `make check`
- [x] Regenerate the manpages, docs and go formatting with `make generated`
- [x] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)

_See [the contribution guide](https://github.com/tektoncd/cli/blob/master/CONTRIBUTING.md)
for more details._

# Release Notes

```release-note
Bump tektoncd/pipeline to v0.44.0 and remove cluster and cloudevent pipelineresource
```

### CODE REVIEW

**Comment by vinamra28** [comment]
@piyush-garg, failure is valid. I guess we'll have to remove 2 tests related to PipelineResources as couple of them have already been deleted

**Review by vinamra28 — APPROVED** [review]
/meow

**Comment by piyush-garg** [comment]
> @piyush-garg, failure is valid. I guess we'll have to remove 2 tests related to PipelineResources as couple of them have already been removed in this release

That was some typo, I fixed that. Already cleaned the tests for the resources which are removed.

**Pull request merged**
