### PR TITLE
Remove golden files generated while testing version command

### PR DESCRIPTION
**Pull request by digglife**
fixes: #1413

# Changes

Remove golden files generated while testing version command, instead, use `assert.Equal`.

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [x] Includes [tests](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if functionality changed/added)
- [x] Run the code checkers with `make check`
- [x] Regenerate the manpages, docs and go formatting with `make generated`
- [x] Commit messages follow [commit message best practices]

# Release Notes

```release-note
NONE
```

### CODE REVIEW

**Comment by vinamra28** [comment]
/ok-to-test
@digglife Thanks for your contribution. Can you please add release-note block as well?

**Comment by digglife** [comment]
@vinamra28 Thanks for guiding me. There is no user facing changes so I add a None block. Hope it's OK.

**Review by vinamra28 — COMMENTED** [review]
/lgtm

**Pull request merged**
